### ISSUE TITLE
More dynamic way of building groups 

### ISSUE THREAD

**Issue by itsjoekent** [DoSomething/messaging-groups-api#4]
Lets clean this block of code up https://github.com/DoSomething/messaging-groups-api/blob/master/lib/routes/api.js#L87

**Comment by aaronschachter** [comment]
@sergii-tkachenko and I were chatting through passing an `environment` parameter to avoid generating 6 groups at once -- instead just generate the doing/completed groups for whatever environment the client is requesting.
